// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVXB1Llw47_uxwrq8Zuc0fLbKPuev-Rkc',
    appId: '1:19691945197:web:18d91d08db9bdacfcd60e4',
    messagingSenderId: '19691945197',
    projectId: 'qringer-b54dd',
    authDomain: 'qringer-b54dd.firebaseapp.com',
    storageBucket: 'qringer-b54dd.firebasestorage.app',
    measurementId: 'G-QTRXFQJFSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB00nYCaQR_2fzKyRCn-ncs9wRtkTZ0m3w',
    appId: '1:19691945197:android:c9536ccf9519c95acd60e4',
    messagingSenderId: '19691945197',
    projectId: 'qringer-b54dd',
    storageBucket: 'qringer-b54dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSiIaRD2o1Z-xT_96uxypTGMAgm1hJZs',
    appId: '1:19691945197:ios:9c4e535dd98d394bcd60e4',
    messagingSenderId: '19691945197',
    projectId: 'qringer-b54dd',
    storageBucket: 'qringer-b54dd.firebasestorage.app',
    iosBundleId: 'com.example.qringerMobileStreamIo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiSiIaRD2o1Z-xT_96uxypTGMAgm1hJZs',
    appId: '1:19691945197:ios:9c4e535dd98d394bcd60e4',
    messagingSenderId: '19691945197',
    projectId: 'qringer-b54dd',
    storageBucket: 'qringer-b54dd.firebasestorage.app',
    iosBundleId: 'com.example.qringerMobileStreamIo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVXB1Llw47_uxwrq8Zuc0fLbKPuev-Rkc',
    appId: '1:19691945197:web:aeea871e4966e430cd60e4',
    messagingSenderId: '19691945197',
    projectId: 'qringer-b54dd',
    authDomain: 'qringer-b54dd.firebaseapp.com',
    storageBucket: 'qringer-b54dd.firebasestorage.app',
    measurementId: 'G-VXM6QRWHB9',
  );

}